using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OSMaker.Classes
{
    class standbox
    {
        // This contain some unclassable fonctions names for OSMaker

        public static string Generate_OS_CPC_contentfile(string OS_name, string OS_SystemName, string MediaPath, string AutorsNames, string CompagnyName, string CreationDate)
        {
            // This allow to create OS.CPC content file with informations

            return 
                @"// ** OS.CPC file generated by OSMaker **" + "\r\n" +
                @"" + "\r\n" +
                @"// Load default gui profile (obligatory)" + "\r\n" +
                @"exe/ & %CPC.REP.KRNL%/CONFIG/ENV_GUI/env_gui.cpc" + "\r\n" +
              
                @"" + "\r\n" +
                @"Screen informations" + "\r\n" +
                @"set/ SCR_RES = 800x600" + "\r\n" +
                @"set/ SCR_BIT = 32" + "\r\n" +
                @"" + "\r\n" +
                @"ccp/ /set.level = 4" + "\r\n" +
                @"" + "\r\n" +
                @"" + "\r\n" +

                @"// **************************************************" + "\r\n" +
                @"// ** [EN] Operating system informations           **" + "\r\n" +
                @"// ** [FR] Informations du systeme d'exploitation  **" + "\r\n" +
                @"// **************************************************" + "\r\n" +
                @"" + "\r\n" +
                @"set/ OS_NAME = " + OS_name + "" + "\r\n" +
                @"set/ OS_Author = " + AutorsNames + "\r\n" +
                @"set/ OS_Compagny = " + CompagnyName + "\r\n" +
                @"set/ OS_Created = " + CreationDate + "\r\n" +
                @"set/ OS_Updated = " + CreationDate + "\r\n" +
                @"" + "\r\n" +
                @"" + "\r\n" +
                @"// ***************************************************" + "\r\n" +
                @"// ** [EN] Operating system configuration           **" + "\r\n" +
                @"// ** [FR] Configuration du systeme d'exploitation  **" + "\r\n" +
                @"// ***************************************************" + "\r\n" +
                @"" + "\r\n" +
                @"set/ HOST_OS = OS/" + OS_SystemName + "\r\n" +
                @"set/ GUI_OS = " + MediaPath + "\r\n" +
                @"" + "\r\n" +
                @"// Background image" + "\r\n" +
                @"set/ SCR_IMG = %GUI_OS%/space.png" + "\r\n" +
                @"" + "\r\n" +
                @"// Screenshot folder" + "\r\n" +
                @"set/ SCR_SAVE = %CPC_TEMP%/SCR" + "\r\n" +
                @"" + "\r\n" +
                @"// ******************************************************" + "\r\n" +
                @"// ** [EN] Starting Graphic User Interface             **" + "\r\n" +
                @"// ** [FR] Demarrer l'interface utilisateur graphique  **" + "\r\n" +
                @"// ******************************************************" + "\r\n" +
                @"gui/ " + "\r\n" +
                @"" + "\r\n" +
                @"// Load icon on GUI" + "\r\n" +
                @"sys/ /fileformat-gui-load" + "\r\n";
        }
    }
}
