// ------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
// Version du runtime :4.0.30319.42000
// 
// Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
// le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace OSMaker.My.Resources
{

    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    /// <summary>
    /// Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("OSMaker.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Remplace la propriété CurrentUICulture du thread actuel pour toutes
        /// les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _62872bookmarktabs_109236
        {
            get
            {
                var obj = ResourceManager.GetObject("62872bookmarktabs_109236", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _62872bookmarktabs_109236__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("_62872bookmarktabs_109236__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _62872bookmarktabs_109236add__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("_62872bookmarktabs_109236add__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _62872bookmarktabs_109236remove__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("_62872bookmarktabs_109236remove__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _property
        {
            get
            {
                var obj = ResourceManager.GetObject("_property", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _property1
        {
            get
            {
                var obj = ResourceManager.GetObject("_property1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap actualiser
        {
            get
            {
                var obj = ResourceManager.GetObject("actualiser", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap add_icon_icons_com_74429__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("add_icon_icons_com_74429__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap add_objet
        {
            get
            {
                var obj = ResourceManager.GetObject("add_objet", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap add_objet2
        {
            get
            {
                var obj = ResourceManager.GetObject("add_objet2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ajouter_marquepage
        {
            get
            {
                var obj = ResourceManager.GetObject("ajouter_marquepage", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrow_left_15601
        {
            get
            {
                var obj = ResourceManager.GetObject("arrow_left_15601", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrow_left_15601_1___Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("arrow_left_15601_1___Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrow_right_15600
        {
            get
            {
                var obj = ResourceManager.GetObject("arrow_right_15600", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrow_right_15600__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("arrow_right_15600__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrows
        {
            get
            {
                var obj = ResourceManager.GetObject("arrows", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrows___Copie
        {
            get
            {
                var obj = ResourceManager.GetObject("arrows___Copie", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap arrows_1_
        {
            get
            {
                var obj = ResourceManager.GetObject("arrows_1_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap backward0_16x16
        {
            get
            {
                var obj = ResourceManager.GetObject("backward0_16x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap backward0_16x161
        {
            get
            {
                var obj = ResourceManager.GetObject("backward0_16x161", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap bar
        {
            get
            {
                var obj = ResourceManager.GetObject("bar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap bookmark__plus
        {
            get
            {
                var obj = ResourceManager.GetObject("bookmark__plus", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap bookmark__plus1
        {
            get
            {
                var obj = ResourceManager.GetObject("bookmark__plus1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Bouton
        {
            get
            {
                var obj = ResourceManager.GetObject("Bouton", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Bouton2
        {
            get
            {
                var obj = ResourceManager.GetObject("Bouton2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap box
        {
            get
            {
                var obj = ResourceManager.GetObject("box", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap box1
        {
            get
            {
                var obj = ResourceManager.GetObject("box1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap button
        {
            get
            {
                var obj = ResourceManager.GetObject("button", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap button_1_
        {
            get
            {
                var obj = ResourceManager.GetObject("button_1_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap bye
        {
            get
            {
                var obj = ResourceManager.GetObject("bye", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap bye1
        {
            get
            {
                var obj = ResourceManager.GetObject("bye1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap calculator
        {
            get
            {
                var obj = ResourceManager.GetObject("calculator", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap checkbox
        {
            get
            {
                var obj = ResourceManager.GetObject("checkbox", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap class_libraries
        {
            get
            {
                var obj = ResourceManager.GetObject("class_libraries", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap class_libraries1
        {
            get
            {
                var obj = ResourceManager.GetObject("class_libraries1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap clipboard
        {
            get
            {
                var obj = ResourceManager.GetObject("clipboard", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap code_cpc_file
        {
            get
            {
                var obj = ResourceManager.GetObject("code_cpc_file", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap code_cpc_file__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("code_cpc_file__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap code_cpc_file1
        {
            get
            {
                var obj = ResourceManager.GetObject("code_cpc_file1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap code_cpc_file2
        {
            get
            {
                var obj = ResourceManager.GetObject("code_cpc_file2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap codingbrowser_102152
        {
            get
            {
                var obj = ResourceManager.GetObject("codingbrowser_102152", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap codingbrowser_102152__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("codingbrowser_102152__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap codingbrowser_1021521
        {
            get
            {
                var obj = ResourceManager.GetObject("codingbrowser_1021521", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap codingbrowser_1021522
        {
            get
            {
                var obj = ResourceManager.GetObject("codingbrowser_1021522", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Comment
        {
            get
            {
                var obj = ResourceManager.GetObject("Comment", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap copy_paste_document_file_1557
        {
            get
            {
                var obj = ResourceManager.GetObject("copy_paste_document_file_1557", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap copy_paste_document_file_1557__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("copy_paste_document_file_1557__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap copy_paste_documents_1580
        {
            get
            {
                var obj = ResourceManager.GetObject("copy_paste_documents_1580", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap copy_paste_documents_1580__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("copy_paste_documents_1580__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap creer
        {
            get
            {
                var obj = ResourceManager.GetObject("creer", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap cross
        {
            get
            {
                var obj = ResourceManager.GetObject("cross", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap cross1
        {
            get
            {
                var obj = ResourceManager.GetObject("cross1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Cut_icon_icons_com_73697
        {
            get
            {
                var obj = ResourceManager.GetObject("Cut_icon_icons_com_73697", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Cut_icon_icons_com_73697__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("Cut_icon_icons_com_73697__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap diamond
        {
            get
            {
                var obj = ResourceManager.GetObject("diamond", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap diamond16
        {
            get
            {
                var obj = ResourceManager.GetObject("diamond16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap diamond161
        {
            get
            {
                var obj = ResourceManager.GetObject("diamond161", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap dna
        {
            get
            {
                var obj = ResourceManager.GetObject("dna", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap dna1
        {
            get
            {
                var obj = ResourceManager.GetObject("dna1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap document
        {
            get
            {
                var obj = ResourceManager.GetObject("document", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap edit_padding_top
        {
            get
            {
                var obj = ResourceManager.GetObject("edit_padding_top", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap edit_padding_top1
        {
            get
            {
                var obj = ResourceManager.GetObject("edit_padding_top1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap emblemsynchronizing_93485
        {
            get
            {
                var obj = ResourceManager.GetObject("emblemsynchronizing_93485", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap eye
        {
            get
            {
                var obj = ResourceManager.GetObject("eye", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap fin
        {
            get
            {
                var obj = ResourceManager.GetObject("fin", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flat_style_circle_redo_icon_icons_com_66947_1_
        {
            get
            {
                var obj = ResourceManager.GetObject("flat_style_circle_redo_icon_icons_com_66947_1_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flat_style_circle_redo_icon_icons_com_66947_1___Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("flat_style_circle_redo_icon_icons_com_66947_1___Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flat_style_circle_undo_icon_icons_com_66949_1_
        {
            get
            {
                var obj = ResourceManager.GetObject("flat_style_circle_undo_icon_icons_com_66949_1_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap flat_style_circle_undo_icon_icons_com_66949_1___Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("flat_style_circle_undo_icon_icons_com_66949_1___Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap folder_2
        {
            get
            {
                var obj = ResourceManager.GetObject("folder-2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap format_textbox_icon_137574
        {
            get
            {
                var obj = ResourceManager.GetObject("format_textbox_icon_137574", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap forward_16x16
        {
            get
            {
                var obj = ResourceManager.GetObject("forward_16x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap forward_16x161
        {
            get
            {
                var obj = ResourceManager.GetObject("forward_16x161", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap gear
        {
            get
            {
                var obj = ResourceManager.GetObject("gear", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap gear_1_
        {
            get
            {
                var obj = ResourceManager.GetObject("gear_1_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap gear_2_
        {
            get
            {
                var obj = ResourceManager.GetObject("gear_2_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap idea
        {
            get
            {
                var obj = ResourceManager.GetObject("idea", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap imagebox
        {
            get
            {
                var obj = ResourceManager.GetObject("imagebox", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap imagebox1
        {
            get
            {
                var obj = ResourceManager.GetObject("imagebox1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap imagebox2
        {
            get
            {
                var obj = ResourceManager.GetObject("imagebox2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap IUG
        {
            get
            {
                var obj = ResourceManager.GetObject("IUG", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap layer__minus
        {
            get
            {
                var obj = ResourceManager.GetObject("layer__minus", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap layer__minus1
        {
            get
            {
                var obj = ResourceManager.GetObject("layer__minus1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap layer__plus
        {
            get
            {
                var obj = ResourceManager.GetObject("layer__plus", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap layer__plus1
        {
            get
            {
                var obj = ResourceManager.GetObject("layer__plus1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap light16
        {
            get
            {
                var obj = ResourceManager.GetObject("light16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap lightning
        {
            get
            {
                var obj = ResourceManager.GetObject("lightning", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap lightning1
        {
            get
            {
                var obj = ResourceManager.GetObject("lightning1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap line_dotted_icon_125232
        {
            get
            {
                var obj = ResourceManager.GetObject("line_dotted_icon_125232", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap line_dotted_icon_125232__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("line_dotted_icon_125232__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap line_dotted_icon_1252321
        {
            get
            {
                var obj = ResourceManager.GetObject("line_dotted_icon_1252321", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap line_dotted_icon_1252322
        {
            get
            {
                var obj = ResourceManager.GetObject("line_dotted_icon_1252322", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap line_dotted_icon_1252323
        {
            get
            {
                var obj = ResourceManager.GetObject("line_dotted_icon_1252323", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap lol
        {
            get
            {
                var obj = ResourceManager.GetObject("lol", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap lol1
        {
            get
            {
                var obj = ResourceManager.GetObject("lol1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap marquepage
        {
            get
            {
                var obj = ResourceManager.GetObject("marquepage", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap marquepage2
        {
            get
            {
                var obj = ResourceManager.GetObject("marquepage2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap openfolderpng
        {
            get
            {
                var obj = ResourceManager.GetObject("openfolderpng", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap openfolderpng1
        {
            get
            {
                var obj = ResourceManager.GetObject("openfolderpng1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OSM_NEW_Project6868
        {
            get
            {
                var obj = ResourceManager.GetObject("OSM_NEW_Project6868", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OSM_OS
        {
            get
            {
                var obj = ResourceManager.GetObject("OSM_OS", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OSM_OS3232
        {
            get
            {
                var obj = ResourceManager.GetObject("OSM_OS3232", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OSM_OS32321
        {
            get
            {
                var obj = ResourceManager.GetObject("OSM_OS32321", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OSMakerIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("OSMakerIcon", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ousuisje
        {
            get
            {
                var obj = ResourceManager.GetObject("ousuisje", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap pen
        {
            get
            {
                var obj = ResourceManager.GetObject("pen", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap pencil
        {
            get
            {
                var obj = ResourceManager.GetObject("pencil", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap printer_text_10868
        {
            get
            {
                var obj = ResourceManager.GetObject("printer_text_10868", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap printer_text_10868__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("printer_text_10868__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap redo
        {
            get
            {
                var obj = ResourceManager.GetObject("redo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap redo_16x16
        {
            get
            {
                var obj = ResourceManager.GetObject("redo_16x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap redo_16x161
        {
            get
            {
                var obj = ResourceManager.GetObject("redo_16x161", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Reduire_Projet
        {
            get
            {
                var obj = ResourceManager.GetObject("Reduire_Projet", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap rolleyes
        {
            get
            {
                var obj = ResourceManager.GetObject("rolleyes", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap rolleyes1
        {
            get
            {
                var obj = ResourceManager.GetObject("rolleyes1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap sad_16x16
        {
            get
            {
                var obj = ResourceManager.GetObject("sad_16x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap sad_16x161
        {
            get
            {
                var obj = ResourceManager.GetObject("sad_16x161", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_37110
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_37110", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_37110__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_37110__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_371101
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_371101", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_371102
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_371102", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save6868
        {
            get
            {
                var obj = ResourceManager.GetObject("Save6868", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap scissors
        {
            get
            {
                var obj = ResourceManager.GetObject("scissors", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap search
        {
            get
            {
                var obj = ResourceManager.GetObject("search", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap smile_16x16
        {
            get
            {
                var obj = ResourceManager.GetObject("smile_16x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap smile_16x161
        {
            get
            {
                var obj = ResourceManager.GetObject("smile_16x161", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap supprimer_mpage
        {
            get
            {
                var obj = ResourceManager.GetObject("supprimer_mpage", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap tabulation
        {
            get
            {
                var obj = ResourceManager.GetObject("tabulation", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap tabulation__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("tabulation__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap tabulation1
        {
            get
            {
                var obj = ResourceManager.GetObject("tabulation1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap tabulation2
        {
            get
            {
                var obj = ResourceManager.GetObject("tabulation2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap tabulation3
        {
            get
            {
                var obj = ResourceManager.GetObject("tabulation3", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap tabulation4
        {
            get
            {
                var obj = ResourceManager.GetObject("tabulation4", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap textebloc
        {
            get
            {
                var obj = ResourceManager.GetObject("textebloc", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap textebox
        {
            get
            {
                var obj = ResourceManager.GetObject("textebox", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap trash
        {
            get
            {
                var obj = ResourceManager.GetObject("trash", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap trash1
        {
            get
            {
                var obj = ResourceManager.GetObject("trash1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap undo
        {
            get
            {
                var obj = ResourceManager.GetObject("undo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap undo_16x16
        {
            get
            {
                var obj = ResourceManager.GetObject("undo_16x16", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap undo_16x161
        {
            get
            {
                var obj = ResourceManager.GetObject("undo_16x161", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap unsure
        {
            get
            {
                var obj = ResourceManager.GetObject("unsure", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap unsure1
        {
            get
            {
                var obj = ResourceManager.GetObject("unsure1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap where_to_vote_117295__Copier_
        {
            get
            {
                var obj = ResourceManager.GetObject("where_to_vote_117295__Copier_", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}