// ------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
// Version du runtime :4.0.30319.42000
// 
// Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
// le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace OSMaker.My
{

    // REMARQUE : Ce fichier étant généré automatiquement, ne le modifiez pas directement.  Pour apporter des modifications,
    // ou si vous rencontrez des erreurs de build dans ce fichier, accédez au Concepteur de projets
    // (allez dans les propriétés du projet ou double-cliquez sur le nœud My Project dans
    // l'Explorateur de solutions), puis apportez vos modifications sous l'onglet Application.
    // 
    internal partial class MyApplication
    {
        [DebuggerStepThrough()]
        public MyApplication() : base(Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
        {
            IsSingleInstance = false;
            EnableVisualStyles = true;
            SaveMySettingsOnExit = true;
            ShutdownStyle = Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose;
        }

        [DebuggerStepThrough()]
        protected override void OnCreateMainForm()
        {
            MainForm = MyProject.Forms.Form2;
        }

        [DebuggerStepThrough()]
        protected override void OnCreateSplashScreen()
        {
            SplashScreen = MyProject.Forms.SplashScreen1;
        }
    }
}