//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSMaker.My {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ouvrir_Page_De_Démarrage {
            get {
                return ((bool)(this["Ouvrir_Page_De_Démarrage"]));
            }
            set {
                this["Ouvrir_Page_De_Démarrage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autoriser_Envoyer_Informations {
            get {
                return ((bool)(this["Autoriser_Envoyer_Informations"]));
            }
            set {
                this["Autoriser_Envoyer_Informations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string Ecran_Demarrage {
            get {
                return ((string)(this["Ecran_Demarrage"]));
            }
            set {
                this["Ecran_Demarrage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Emplacement_Project_Par_Defaut {
            get {
                return ((string)(this["Emplacement_Project_Par_Defaut"]));
            }
            set {
                this["Emplacement_Project_Par_Defaut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Projets_Recents {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Projets_Recents"]));
            }
            set {
                this["Projets_Recents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Société {
            get {
                return ((string)(this["Société"]));
            }
            set {
                this["Société"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Réduire_Panneau_Lateral_WindowsDesigner {
            get {
                return ((bool)(this["Réduire_Panneau_Lateral_WindowsDesigner"]));
            }
            set {
                this["Réduire_Panneau_Lateral_WindowsDesigner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Suivre_Souris_Regle {
            get {
                return ((bool)(this["Suivre_Souris_Regle"]));
            }
            set {
                this["Suivre_Souris_Regle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Afficher_La_Griller {
            get {
                return ((bool)(this["Afficher_La_Griller"]));
            }
            set {
                this["Afficher_La_Griller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Smart_Tags {
            get {
                return ((bool)(this["Smart_Tags"]));
            }
            set {
                this["Smart_Tags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Aimentation_Intelligente {
            get {
                return ((bool)(this["Aimentation_Intelligente"]));
            }
            set {
                this["Aimentation_Intelligente"] = value;
            }
        }
    }
}
